### ISSUE TITLE
Multiple Bookings with Multiple Products?

### ISSUE THREAD

**Issue by ricks03** [blazeteam/events-manager-booking-payments-with-woocommerce#5]
If I have two different Bookings in Events Manager, can I have two different WooCommerce products, each tied to a separate booking?

If I have two Events Manager Bookings, each with a different price, there's no way to create a separate product for each.

**Comment by andrewreal** [comment]
Hi,

You only need the one "Event Booking" product as that is just to add the total cost of the bookings together and apply to the cart for the transaction. The booking data is still stored as two separate bookings.

Hope that helps

Andrew

**Comment by ricks03** [comment]
That helps. That's works!  This is great.
